export const FETCH_QUOTES_IN_PROGRESS = 'FETCH_QUOTES_IN_PROGRESS';
export const FETCH_QUOTES_SUCCESSES = 'FETCH_QUOTES_SUCCESSES';
export const FETCH_QUOTES_FAILED = 'FETCH_QUOTES_FAILED';

export const FETCH_QUOTES = 'FETCH_QUOTES';